### ISSUE TITLE
Remix route error from console

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/storefront-remix-starter#9] opened 2022-06-10 17:40 UTC
Hello,

I am getting following error from browser console, not sure if it's reason why the "Wish list" feature not functional or it's still not deployed.

```
Warning: Did not expect server HTML to contain a <script> in <body>.
footer
Footer@https://store.abc.com/build/root-REVYTQJD.js:282:16
body
html
App@https://store.abc.com/build/root-REVYTQJD.js:446:55
RemixRoute@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:2588:20
Routes2@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:2572:7
Router@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:688:7
RemixCatchBoundary@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:1081:28
RemixErrorBoundary@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:1007:5
RemixEntry@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:2468:20
RemixBrowser@https://store.abc.com/build/_shared/chunk-AM7YLLF5.js:3223:27 react-dom.development.js:67:29

```

How could i solve it?

Thank you.

**Comment by michaelbromley** [comment] 2022-06-11 10:15
The wish list part is non-functional because Vendure by default does not ship with wishlist functionality. It's there more as an example for the layout, a bit like with the reviews.

Regarding that error message - under what circumstances does it appear? What steps would I need to do do reproduce it?

**Comment by blackyzero** [comment] 2022-06-13 13:44
Got it thanks @michaelbromley.
I also checked other storefronts, and seems those features are already added. it would be great to have those features available on Remix storefront.

About the error message, i just browse the first page with browser console open, and it appears after paged loaded.
You can see more detail in attached screenshot.

![Screen Shot 2022-06-13 at 9 39 52 AM](https://user-images.githubusercontent.com/4286063/173367297-0000d61e-236f-4387-9d98-b5caa2760076.png)

Thank you.

**Comment by kyunal** [comment] 2022-11-24 12:33
This is most likely not an issue from the storefront itself. As stated in the Remix docs, this can occur with browser extensions injecting scripts into the page: https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code

Closing this as I haven't been able to reproduce it outside of this.

**Closed by kyunal** 2022-11-24 12:33 UTC

**Comment by blackyzero** [comment] 2022-11-26 02:34
Great. Thanks for sharing !
